### ISSUE TITLE
Occasionally will get "No Edge TPU device detected!"

### ISSUE THREAD

**Issue by patcombe** [cxl-garage/wallflwr_lite#26]
Sometimes I will receive the above error. A restart will typically fix it.

![Screen Shot 2020-12-01 at 10 15 19 AM](https://user-images.githubusercontent.com/68561971/100764882-d67c2980-33c4-11eb-8712-9a8517f1cab2.png)

**Comment by sim-kelly** [comment]
This is similar fix to #28. Will add timer/restart
