### ISSUE TITLE
Group confidence incorrect

### ISSUE THREAD

**Issue by patcombe** [cxl-garage/wallflwr_lite#30]
@sim-kelly I need to fix this but I not sure what the group confidence should be. Is it just all those in that group's individual confidence's summed?

**Comment by sim-kelly** [comment]
Currently - yes. Let me see if there is some literature around dependent/grouped inference

**Comment by sim-kelly** [comment]
How is it "incorrect?"

**Comment by patcombe** [comment]
I assumed it was a summation of all for that group, that isnt the case right now 
![Screen Shot 2020-12-01 at 11 58 28 AM](https://user-images.githubusercontent.com/68561971/100771544-8739f700-33cc-11eb-9804-71b9913ed1b9.png)

**Comment by patcombe** [comment]
prob cause I changed how group key is done
